# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
Personaidentify Environment Implementation.

Tasks 1 and 2 run across 5 users per episode. After each user the agent
receives an intermediate observation (done=False, reward for that user).
After the 5th user the episode ends (done=True).

Task 3 is a single-user cold-start dialogue episode:
  - reset() returns a start_intro generated by an evaluator LLM impersonating
    the user, along with the full persona catalogue so the agent knows its options.
  - The agent may send up to MAX_QUESTIONS actions with text_question set.
    Each one is answered by the evaluator LLM in character (text_reply).
  - Once the agent sends an action with predictions + ranked_products (and no
    text_question), the episode ends and is scored by task3_evaluator().
  - If the agent exhausts the question budget without recommending, the next
    step call that carries a question is rejected and it must recommend instead.
"""

from uuid import uuid4

import json
import random

from openenv.core.env_server.interfaces import Environment
from openenv.core.env_server.types import State

try:
    from ..models import PersonaIdentifyAction, PersonaIdentifyObservation, PersonaIdentifyState
    from ..datamodels import ProductReview
    from ..evalhelpers import calculate_persona_reward, calculate_product_ranking_reward, task3_evaluator, MAXQ
    from ..utils import get_all_personas, get_personas, make_basket, get_real_purchases
    from ..llm import PersistentLLMHelper
except ImportError:
    from models import PersonaIdentifyAction, PersonaIdentifyObservation, PersonaIdentifyState
    from datamodels import ProductReview
    from evalhelpers import calculate_persona_reward, calculate_product_ranking_reward, task3_evaluator, MAXQ
    from utils import get_all_personas, get_personas, make_basket, get_real_purchases
    from llm import PersistentLLMHelper


USERS_PER_EPISODE = 5
MAX_QUESTIONS = MAXQ

# System prompt for the evaluator LLM in Task 3.
# {persona} and {history} are filled in per episode.
_EVALUATOR_SYSTEM_PROMPT = """You are roleplaying as a real online shopper.

Your persona: {persona}

Your purchase history:
{history}

Here is an explanation of all your personas:
{explanations}

Rules:
- Stay fully in character as this shopper at all times.
- Answer questions naturally and conversationally.
- Never directly state your persona label or list your purchases verbatim.
- Never break character or acknowledge that you are an AI.
- The user on the other hand is an AI. Treat it as such. you are a human the user is not. It is a recommender AI.
"""

_INTRO_PROMPT = (
    "Introduce yourself briefly as a shopper. Mention what kinds of things you "
    "generally enjoy or look for when shopping, without listing specific purchases. "
    "Keep it to 2-3 sentences."
)


class PersonaidentifyEnvironment(Environment):
    """
    Personaidentify environment.

    Tasks 1 & 2: 5-user episodes, one step per user, reward returned each step.
    Task 3: single-user dialogue episode with up to MAX_QUESTIONS Q&A turns
            followed by a final recommendation action.
    """

    SUPPORTS_CONCURRENT_SESSIONS: bool = False

    def __init__(self):
        self._state = PersonaIdentifyState(episode_id=str(uuid4()), step_count=0, user_id="", task=1)
        self._reset_count = 0

        self.DATA = json.load(open("server/user_personas.json"))
        self.PERSONADATA = json.load(open("server/persona_catalogue.json"))

        # Tasks 1 & 2 — multi-user episode tracking
        self._user_queue: list[dict] = []
        self._current_user: dict = {}
        self._user_index: int = 0

        # Task 3 — dialogue state
        self._t3_evaluator: PersistentLLMHelper | None = None
        self._t3_questions_asked: int = 0

        self.task: int = 1

    # ------------------------------------------------------------------
    # Helpers — Tasks 1 & 2
    # ------------------------------------------------------------------

    def _sample_user_queue(self) -> list[dict]:
        """Sample USERS_PER_EPISODE distinct users for one episode."""
        return random.sample(self.DATA, k=min(USERS_PER_EPISODE, len(self.DATA)))

    def _load_current_user(self) -> None:
        """Point internal state at the user at _user_index in the queue."""
        self._current_user = self._user_queue[self._user_index]
        self._state.user_id = self._current_user["user_id"]

    def _observation_for_task1(self, *, done: bool, reward: float) -> PersonaIdentifyObservation:
        purchase_history = [
            ProductReview(
                title=item["title"],
                rating=item["rating"],
                price=item["price"],
                description=item["description"],
                review_text=item["review_text"],
            )
            for item in self._current_user["purchase_history"]
        ]
        return PersonaIdentifyObservation(
            done=done,
            reward=reward,
            task=1,
            purchase_history=purchase_history,
            personas=get_all_personas(self.PERSONADATA),
            users_remaining=USERS_PER_EPISODE - self._user_index - (1 if done else 0),
        )

    def _observation_for_task2(self, *, done: bool, reward: float) -> PersonaIdentifyObservation:
        uid = self._current_user["user_id"]
        return PersonaIdentifyObservation(
            task=2,
            done=done,
            reward=reward,
            personas=get_all_personas(self.PERSONADATA),
            basket=make_basket(self.DATA, uid),
            persona_labels=get_personas(self.DATA, uid),
            users_remaining=USERS_PER_EPISODE - self._user_index - (1 if done else 0),
        )

    # ------------------------------------------------------------------
    # Helpers — Task 3
    # ------------------------------------------------------------------

    def _build_evaluator_system_prompt(self, user: dict) -> str:
        """Fill in the evaluator system prompt with this user's details."""
        allPersonas = get_all_personas(self.PERSONADATA)
        userPersona = get_personas(self.DATA, user['user_id'])
        userPersonaNames = [p.persona for p in userPersona]
        personaExplanations = [{"name":p.name, "description":p.description,"signals":p.signals} for p in allPersonas if p.name in userPersonaNames]

        persona_str = json.dumps([{"persona": p.persona, "confidence": p.confidence} for p in userPersona], indent=2)
        persona_explanation_str = json.dumps(personaExplanations, indent=2)
        history_str = "\n".join(
            f"- {item['title']} (rated {item['rating']}/5, ${item['price']})"
            for item in user["purchase_history"]
        )
        return _EVALUATOR_SYSTEM_PROMPT.format(persona=persona_str, history=history_str, explanations=persona_explanation_str)

    def _reset_task3(self) -> PersonaIdentifyObservation:
        """
        Initialise a Task-3 episode for a single randomly chosen user.
        Spins up a fresh PersistentLLMHelper seeded with the evaluator
        system prompt, then generates the opening intro message.
        """

        self._current_user = random.choice(self.DATA)
        self._state.user_id = self._current_user["user_id"]
        self._t3_questions_asked = 0

        system_prompt = self._build_evaluator_system_prompt(self._current_user)
        self._t3_evaluator = PersistentLLMHelper(system_prompt=system_prompt)

        start_intro = self._t3_evaluator.prompt(_INTRO_PROMPT)

        return PersonaIdentifyObservation(
            task=3,
            done=False,
            reward=0.0,
            personas=get_all_personas(self.PERSONADATA),
            start_intro=start_intro,
        )

    def _step_task3(self, action: PersonaIdentifyAction) -> PersonaIdentifyObservation:
        """
        Handle one Task-3 step.

        Question turn  (action.text_question is set):
          - Forward to evaluator LLM and return its reply via text_reply.
          - If question budget is already exhausted, reject with a system
            message and prompt the agent to recommend instead.

        Recommendation turn (action.text_question is None):
          - Score via task3_evaluator() and end the episode.
        """
        self._state.step_count += 1

        # ---- Question turn ---------------------------------------------
        if action.text_question:
            if self._t3_questions_asked >= MAX_QUESTIONS:
                # Budget exhausted — force the agent to recommend
                return PersonaIdentifyObservation(
                    task=3,
                    done=False,
                    reward=0.0,
                    text_reply=(
                        "[System: question budget exhausted. "
                        "You must now submit your recommendation.]"
                    ),
                )

            self._t3_questions_asked += 1
            reply = self._t3_evaluator.prompt(action.text_question)

            return PersonaIdentifyObservation(
                task=3,
                done=False,
                reward=0.0,
                text_reply=reply,
            )

        # ---- Recommendation turn ---------------------------------------
        true_personas = self._current_user["persona"]["all"]
        purchase_history = get_real_purchases(self.DATA, self._current_user['user_id'])

        reward = task3_evaluator(
            pred_actions=action.predictions,
            ranked_products=action.ranked_products,
            true_personas_list=true_personas,
            purchase_history=purchase_history,
            numq=self._t3_questions_asked,
        )

        return PersonaIdentifyObservation(
            task=3,
            done=True,
            reward=reward,
        )

    # ------------------------------------------------------------------
    # Core API
    # ------------------------------------------------------------------

    def reset(self, task: int = 3) -> PersonaIdentifyObservation:
        """Reset the environment and start a fresh episode."""
        self.task = task
        self._reset_count += 1

        self._state = PersonaIdentifyState(
            episode_id=str(uuid4()),
            step_count=0,
            user_id="",
            task=self.task,
        )

        if task == 3:
            return self._reset_task3()

        # Tasks 1 & 2 — sample a queue of 5 users
        self._user_queue = self._sample_user_queue()
        self._user_index = 0
        self._load_current_user()

        if task == 2:
            return self._observation_for_task2(done=False, reward=0.0)

        return self._observation_for_task1(done=False, reward=0.0)

    def step(self, action: PersonaIdentifyAction) -> PersonaIdentifyObservation:
        """Execute one environment step."""
        assert self.task == action.task, (
            f"Action task {action.task} does not match episode task {self.task}"
        )

        if self.task == 3:
            return self._step_task3(action)

        self._state.step_count += 1
        uid = self._current_user["user_id"]

        # ---- Score current user (Tasks 1 & 2) --------------------------
        if self.task == 2:
            step_reward = calculate_product_ranking_reward(
                get_real_purchases(self.DATA, uid), action.ranked_products
            )
        else:
            step_reward = calculate_persona_reward(
                self._current_user["persona"]["all"], action.predictions
            )

        self._user_index += 1
        episode_done = self._user_index >= USERS_PER_EPISODE

        if episode_done:
            return PersonaIdentifyObservation(
                task=self.task,
                done=True,
                reward=step_reward,
                users_remaining=0,
            )

        self._load_current_user()

        if self.task == 2:
            return self._observation_for_task2(done=False, reward=step_reward)

        return self._observation_for_task1(done=False, reward=step_reward)

    @property
    def state(self) -> PersonaIdentifyState:
        return self._state